import turtle as tmi
r1 = 30   #小半径
r2 = 50   #大半径
h = 170   #总高度
d1 = 40   #线宽
d2 = 30   #线距
tmi.fillcolor("orangered")
tmi.pu()
tmi.goto(-90,-200)
tmi.pencolor("orangered")
tmi.pd()
tmi.begin_fill()
for i in range(4):
    tmi.fd(150)
    tmi.circle(150,90)
tmi.end_fill()
tmi.pencolor("white")
tmi.fillcolor("white")
tmi.pu()
tmi.goto(0,-50)
tmi.pd()
tmi.begin_fill()
tmi.fd(d1)
tmi.lt(90)
tmi.fd(h-r2)
tmi.circle(r2,90)
tmi.fd(3*d1+2*d2-r2)
tmi.lt(90)
tmi.fd(h)
tmi.lt(90)
tmi.fd(d1)
tmi.end_fill()
tmi.fillcolor("orangered")
tmi.begin_fill()
tmi.pu()
tmi.goto(0,-50)
tmi.pd()
tmi.seth(90)
tmi.fd(h-d1-r1)
tmi.circle(r1,90)
tmi.fd(d1+d2)
tmi.lt(90)
tmi.fd(h-d1)
tmi.end_fill()
tmi.fillcolor("white")
tmi.begin_fill()
tmi.pu()
tmi.goto(0-d2,-50)
tmi.pd()
tmi.seth(90)
for j in range(2):
    tmi.fd(h-d1-r1)
    tmi.lt(90)
    tmi.fd(d1)
    tmi.lt(90)
tmi.end_fill()
tmi.fillcolor("white")
tmi.begin_fill()
tmi.pu()
tmi.goto(0+d1+d2,-50)
tmi.pd()
tmi.seth(90)
for j in range(2):
    tmi.fd(h)
    tmi.rt(90)
    tmi.fd(d1)
    tmi.rt(90)
tmi.end_fill()
tmi.ht()
xitonclick()
